### PR TITLE
Add support for RISC-V

### PR DESCRIPTION
**Pull request by yuzibo**
This is PR duplicated from
https://github.com/vstinner/python-ptrace/pull/75
All code from Andreas Schwab <schwab@suse.de>

Signed-off-by: Andreas Schwab <schwab@suse.de>

### CODE REVIEW

**Comment by yuzibo** [comment]
First I hope this is a right way to send another PR based on others' PR on github.
In my understanding, I have no permission to edit/update commit on others' PR.

I have fixed some formatting issues and run test cases on my Unmatched board.
Please let me know if there is any issues.
Thanks.

**Comment by spoutn1k** [comment]
It will work. Thank you for your work and being respectful of Andreas'. I pushed a fix for the github workflows, and if @vstinner does not merge it in the week, I will.

**Comment by yuzibo** [comment]
Many thanks.

Btw, do we have plan to support python3.11 also(your commit hit me)? This time I build&test python-ptrace on python3.11:
```python
...
OK
pep8 inst-nodeps: /home/vimer/build/python/python-ptrace/python-ptrace/.tox/.tmp/package/1/python-ptrace-0.9.9.zip
pep8 installed: flake8==6.0.0,mccabe==0.7.0,pycodestyle==2.10.0,pyflakes==3.0.1,python-ptrace @ file:///home/vimer/build/python/python-ptrace/python-ptrace/.tox/.tmp/package/1/python-ptrace-0.9.9.zip
pep8 run-test-pre: PYTHONHASHSEED='3171247802'
pep8 run-test: commands[0] | flake8 ptrace/ tests/ gdb.py runtests.py setup_cptrace.py setup.py strace.py SYSCALL_PROTOTYPES.codegen.py test_doc.py
________________________________________________________________ summary ________________________________________________________________
  py3: commands succeeded
  pep8: commands succeeded
  congratulations :)
vimer@dev-rv-unmatched:~/build/python/python-ptrace/python-ptrace$ python3 --version
Python 3.11.1
vimer@dev-rv-unmatched:~/build/python/python-ptrace/python-ptrace$ uname -a
Linux dev-rv-unmatched 6.1.0-1-riscv64 #1 SMP Debian 6.1.4-1 (2023-01-07) riscv64 GNU/Linux
```
AFAIK, Debian maybe uses python3.11 as the default version for bookworm(Although there is still debate, but they really did a lot of work for this). I think more and more linux distributions will use python3.11.

So, I can send PR after the PR can be merged if this makes sense. There is no extra work to do here.:)

**Comment by spoutn1k** [comment]
I don't see why not ! If you would like to push a PR be my guest. There may be some references to the python version to update in the documentation as well.

**Comment by yuzibo** [comment]
OK, will do.:)

**Comment by vstinner** [comment]
Nice contribution! Thanks. What's your use case for python-ptrace?

**Pull request merged**
