### PR TITLE
Add support for RISC-V

### PR DESCRIPTION
**Pull request by andreas-schwab**
Only tested on riscv64, as openSUSE has no support for riscv32.

### CODE REVIEW

**Comment by spoutn1k** [comment]
Looking good ! Please fix the formatting issues reported by the linter. Run `tox` in the project directory to have them listed !

**Comment by andreas-schwab** [comment]
I'm not responsible for the formatting issues.

**Comment by spoutn1k** [comment]
That is correct. I did not check before as the files matched, sorry about that.

**Comment by yuzibo** [comment]
Hi,

I am interested to help to fix formatting issues and tested it on riscv64 real hardware.
How can do it? Do I open a new PR based on the PR or others better way? thanks.

**Comment by spoutn1k** [comment]
Merged in #76.

**Pull request closed without merging**
